apple:
  computername: "Krish's M1"
  hostname: "krishg"
  localhostname: "krishg"

git:
  config:
    user:
      name: "Krish Gupta"
      email: "135469703+kkrishguptaa@users.noreply.github.com"

github:
  username: kkrishguptaa
