pager: "less"
progress: true
verbose: true
completion: true
diff:
  pager: "delta"
edit:
  command: "code"
  args: ["--wait"]
merge:
  command: "bash"
  args:
  - "-c"
  - "cp {{ .Target }} {{ .Target }}.base && code --new-window --wait --merge {{ .Destination }} {{ .Target }} {{ .Target }}.base {{ .Source }}"
