apple:
  computername: "Krish's MacBook"
  hostname: "kkrishguptaa"
  localhostname: "kkrishguptaa.local"

git:
  config:
    user:
      name: "Krish Gupta"
      email: "m.krishggupta@icloud.com"

github:
  username: kkrishguptaa
