apple:
  computername: "Krish's MacBook"
  hostname: "krishg"
  localhostname: "krishg"

git:
  config:
    user:
      name: "Krish Gupta"
      email: "krish@krishg.com"

github:
  username: kkrishguptaa
